import { DonationObjectFactory } from '#database/factories/donation_object_factory'
import DonationObject from '#models/donation-object'
import { BaseSeeder } from '@adonisjs/lucid/seeders'
import { DateTime } from 'luxon'

export default class extends BaseSeeder {
  async run() {
    const objects = [
      {
        name: 'Ballon de foot',
        description: 'Légèrement usé, taille 5',
        type: true,
        status: 1,
        categorie: 'sport',
        userId: 1,
        imagePath: 't4n41e8b0sbcerfn7rxgwz4y.webp',
        availableFrom: DateTime.now(),
        availableUntil: DateTime.now().plus({ days: 7 }),
        urgent: true,
      },
      {
        name: 'Ballon de basket',
        description: 'Coupe du monde 2015, excellent état',
        type: false,
        status: 1,
        categorie: 'sport',
        userId: 1,
        imagePath: 't4n41e8b0sbcerfn7rxgwz4y.webp',
        urgent: true,
      },
      {
        name: 'Livre - Le Seigneur des Anneaux',
        description: 'Trilogie complète, édition de poche',
        type: true,
        status: 1,
        categorie: 'books',
        userId: 1,
        imagePath: 't4n41e8b0sbcerfn7rxgwz4y.webp',
        availableFrom: DateTime.now(),
        availableUntil: DateTime.now().plus({ days: 7 }),
        urgent: true,
      },
      {
        name: "Veste d'hiver",
        description: 'Taille M, couleur bleu marine, très chaude',
        type: true,
        status: 1,
        categorie: 'clothes',
        userId: 1,
        imagePath: 't4n41e8b0sbcerfn7rxgwz4y.webp',
        availableFrom: DateTime.now(),
        availableUntil: DateTime.now().plus({ days: 7 }),
        urgent: true,
      },
      {
        name: 'Console de jeu (ancienne génération)',
        description: 'Fonctionnelle, vendue sans manettes',
        type: false,
        status: 2,
        categorie: 'tech',
        userId: 1,
        imagePath: 't4n41e8b0sbcerfn7rxgwz4y.webp',
        urgent: true,
      },
      {
        name: 'Assiettes en porcelaine',
        description: 'Lot de 6 assiettes plates blanches',
        type: true,
        status: 1,
        categorie: 'home',
        userId: 1,
        imagePath: 't4n41e8b0sbcerfn7rxgwz4y.webp',
        availableFrom: DateTime.now(),
        availableUntil: DateTime.now().plus({ days: 7 }),
        urgent: true,
      },
      {
        name: 'Tapis de Yoda',
        description: 'Neuf, couleur verte, épaisseur 5mm',
        type: true,
        status: 1,
        categorie: 'sport',
        userId: 1,
        imagePath: 't4n41e8b0sbcerfn7rxgwz4y.webp',
        availableFrom: DateTime.now(),
        availableUntil: DateTime.now().plus({ days: 7 }),
        urgent: true,
      },
      {
        name: 'Ordinateur portable',
        description: 'Écran fissuré, pour pièces uniquement',
        type: false,
        status: 3,
        categorie: 'tech',
        userId: 1,
        imagePath: 't4n41e8b0sbcerfn7rxgwz4y.webp',
      },
      {
        name: 'Jeu de construction pour enfants',
        description: 'Boîte presque complète (quelques pièces manquantes)',
        type: true,
        status: 1,
        categorie: 'toys',
        userId: 1,
        imagePath: 't4n41e8b0sbcerfn7rxgwz4y.webp',
        availableFrom: DateTime.now(),
        availableUntil: DateTime.now().plus({ days: 7 }),
      },
      {
        name: 'Chaussures de randonnée',
        description: 'Taille 42, très bon état',
        type: true,
        status: 1,
        categorie: 'clothes',
        userId: 1,
        imagePath: 't4n41e8b0sbcerfn7rxgwz4y.webp',
        availableFrom: DateTime.now(),
        availableUntil: DateTime.now().plus({ days: 7 }),
      },
      {
        name: 'Micro-ondes',
        description: 'Fonctionne parfaitement, couleur noire',
        type: false,
        status: 1,
        categorie: 'appliances',
        userId: 1,
        imagePath: 't4n41e8b0sbcerfn7rxgwz4y.webp',
      },
      {
        name: 'Guitare acoustique',
        description: 'Corde de Mi grave cassée',
        type: true,
        status: 2,
        categorie: 'art',
        userId: 1,
        imagePath: 't4n41e8b0sbcerfn7rxgwz4y.webp',
        availableFrom: DateTime.now(),
        availableUntil: DateTime.now().plus({ days: 7 }),
      },
      {
        name: 'Lot de stylos et crayons',
        description: 'Matériel de bureau neuf',
        type: true,
        status: 1,
        categorie: 'office',
        userId: 1,
        imagePath: 't4n41e8b0sbcerfn7rxgwz4y.webp',
        availableFrom: DateTime.now(),
        availableUntil: DateTime.now().plus({ days: 7 }),
      },
      {
        name: 'Écran PC 24 pouces',
        description: 'Moniteur Full HD, quelques légères rayures',
        type: false,
        status: 1,
        categorie: 'tech',
        userId: 1,
        imagePath: 't4n41e8b0sbcerfn7rxgwz4y.webp',
      },
      {
        name: 'AMD EPYC 9965',
        description: 'AMD EPYC 9965 est un processeur serveur haut de gamme...',
        type: true,
        status: 1,
        categorie: 'tech',
        userId: 1,
        imagePath: 't4n41e8b0sbcerfn7rxgwz4y.webp',
        availableFrom: DateTime.now(),
        availableUntil: DateTime.now().plus({ days: 7 }),
      },
    ]

    // // On crée les objets définis ci-dessus
    await DonationObject.createMany(objects)


    await DonationObjectFactory.createMany(10000)
  }
}
