services:
  je-donne-je-prete:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
    env_file:
      - .env
    image: je-donne-je-prete:latest
    container_name: je-donne-je-prete
    ports:
      - '0.0.0.0:${PORT}:${PORT}'
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
      - DB_HOST=${DB_HOST}
    restart: always

  db1:
    image: mariadb:12.1
    container_name: db1
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
