name: CI Tests
on:
  push:
    branches:
      - main
      - 'Release*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Migrations and Tests
        run: |
          node ace migration:run --force
          npm test
        env:
          NODE_ENV: test
          DB_CONNECTION: sqlite
          PORT: 3333
          HOST: 0.0.0.0
          APP_KEY: ${{ secrets.APP_KEY || 'votre_cle_secrete_de_32_caracteres_mini' }}
          LOG_LEVEL: info
          SESSION_DRIVER: cookie
          DB_TYPE: sqlite
          DB_HOST: localhost
          DB_PORT: 3306
          DB_USER: root
          DB_PASSWORD: ''
          DB_DATABASE: testing